source "http://rubygems.org"
gem "rack-cache","=1.0.3"
gem "activesupport","=3.1"
gem "activeresource","=3.1.0"
gem "actionpack","=3.1.0"
gem "actionmailer","=3.1.0"
gem "activerecord","=3.1.0"
gem "rails","=3.1.0"
gem "railties","=3.1.0"
gem "jdbc-mysql", "=5.1.13"
gem "xml-simple", "=1.0.12"
gem "fastercsv", "=1.5.3"
gem "hpricot", "=0.8.2"
gem "newrelic_rpm", "=3.1.1"
gem "mime-types", "=1.16"
gem "warbler","=1.3.0"
gem "rmagick4j","=0.3.7"
gem "starling","=0.10.1"
gem "jruby-memcache-client","=1.7.0"
gem "jruby-jars","=1.5.6"
gem "jruby-rack","=1.0.9"
gem "activerecord-jdbc-adapter","=1.2.1"
gem "activerecord-jdbcmysql-adapter", "=1.2.1"
gem "net-ldap", "=0.2.2"
gem "jruby-openssl", "=0.7.3"
gem "prototype-rails","=3.1.0"
gem "builder","=3.0.0"
gem "i18n","=0.6.0"
gem "rack","=1.3.5"
gem "rack-test","=0.6.1"
gem "rack-mount","=0.8.3"
gem "rdoc","=3.11"
gem "rack-ssl","=1.3.2"
gem "hike","=1.2.1"
gem "sprockets","=2.0.3"
gem "multi_json","=1.0.3"
gem "bcrypt-ruby","=3.0.1"
gem "crack","=0.1.1"
gem "ruby-debug", "= 0.10.4"
gem "ruby-debug-base", "= 0.10.4"
gem 'nokogiri'

platforms :jruby do
   
  # This is needed by now to let tests work on JRuby
  # TODO: When the JRuby guys merge jruby-openssl in
  # jruby this will be removed
  #gem "jruby-openssl"
end
